"""Initial

Revision ID: 0c8a8c150357
Revises: 
Create Date: 2026-02-22 19:30:33.595242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c8a8c150357'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=100), nullable=False),
    sa.Column('stop_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    op.create_table('stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number'),
    schema='partners'
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clients'
    )
    op.create_table('stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['common.lines.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['common.stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    op.create_table('partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='partners'
    )
    op.create_table('scheduled_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_city', sa.String(length=100), nullable=False),
    sa.Column('arrival_city', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('driver_phone', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['partners.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='partners'
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clients'
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('number_of_seats', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('passenger_name', sa.String(length=100), nullable=False),
    sa.Column('passenger_phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['partners.scheduled_trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clients'
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TRANSPORT_FEES', 'WALLET_CREDITING', name='client_transaction_type', schema='clients'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('departure', sa.String(length=100), nullable=True),
    sa.Column('arrival', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.Enum('WALLET', 'OM', 'MOMO', 'MM', 'WAVE', 'CREDIT_CARD', 'CASH', name='client_payment_method', schema='clients'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clients'
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clients'
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='partners'
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TRANSPORT_FEES', 'WITHDRAWL', name='partner_transaction_type', schema='partners'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('departure', sa.String(length=100), nullable=True),
    sa.Column('arrival', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.Enum('WALLET', 'OM', 'MOMO', 'MM', 'WAVE', 'CREDIT_CARD', 'CASH', name='partner_payment_method', schema='partners'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='partners'
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_provider_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['clients.bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('transaction_id'),
    schema='clients'
    )
    op.create_table('steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('client_transaction_id', sa.UUID(), nullable=False),
    sa.Column('partner_transaction_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('departure', sa.String(length=100), nullable=False),
    sa.Column('arrival', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_transaction_id'], ['clients.transactions.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partners.id'], ),
    sa.ForeignKeyConstraint(['partner_transaction_id'], ['partners.transactions.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['clients.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_trips_arrival'))
        batch_op.drop_index(batch_op.f('idx_trips_departure'))
        batch_op.drop_index(batch_op.f('idx_trips_departure_time'))

    op.drop_table('trips')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bookings_trip_id'))
        batch_op.drop_index(batch_op.f('idx_bookings_user_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_booking_id'))
        batch_op.drop_index(batch_op.f('idx_payments_transaction_id'))

    op.drop_table('payments')
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('stops_line_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lines', ['line_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('stops_line_id_fkey'), 'lines', ['line_id'], ['id'])

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_provider_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('payments_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('booking_id', name=op.f('payments_booking_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('transaction_id', name=op.f('payments_transaction_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payments_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_booking_id'), ['booking_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_of_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('passenger_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('passenger_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('bookings_trip_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_bookings_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_bookings_trip_id'), ['trip_id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departure_city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('arrival_city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('departure_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('arrival_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('available_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('driver_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trips_pkey'))
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_trips_departure_time'), ['departure_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_trips_departure'), ['departure_city'], unique=False)
        batch_op.create_index(batch_op.f('idx_trips_arrival'), ['arrival_city'], unique=False)

    op.drop_table('steps', schema='common')
    op.drop_table('payments', schema='clients')
    op.drop_table('transactions', schema='partners')
    op.drop_table('accounts', schema='partners')
    op.drop_table('trips', schema='clients')
    op.drop_table('transactions', schema='clients')
    op.drop_table('bookings', schema='clients')
    op.drop_table('accounts', schema='clients')
    op.drop_table('scheduled_trips', schema='partners')
    op.drop_table('partners', schema='partners')
    op.drop_table('stops', schema='common')
    op.drop_table('clients', schema='clients')
    op.drop_table('vehicles', schema='partners')
    op.drop_table('stations', schema='common')
    op.drop_table('lines', schema='common')
    # ### end Alembic commands ###
